## Package update notes

### Latest branch
<!-- Branch spring2022.  -->
sprint 2023

### Build

```{r, eval=FALSE}
devtools::install(build_vignettes = TRUE, dependencies = FALSE)
devtools::install_github("agroimpacts/geospaar", build_vignettes = TRUE)
```


That gets the two core pieces of the website. Now have to write vignettes into there. 
```{r, eval=FALSE}
rmds <- dir(here::here("vignettes"), pattern = "Rmd", full.names = TRUE)

for(i in 1:length(rmds)) {
  print(i)
  ifile <- rmds[i]
  print(ifile)
  ohtml <- here::here("docs", 
                      paste0(gsub("\\.Rmd", "", basename(ifile)), ".html"))
  # print(glue::glue("Writing {basename(ohtml)}"))
  # print(ohtml)
  rmarkdown::render(input = ifile,
                    output_file = ohtml)
}
```

```{r, eval=FALSE}
rmds <- dir(here::here("vignettes"), pattern = "Rmd", full.names = TRUE)
# render specific files
# ifile <- rmds[grep("software-installation", rmds)]
# ifile <- rmds[grep("cheatsheets", rmds)]
# ifile <- rmds[grep("git", rmds)]
# ifile <- rmds[grep("unit1.Rmd", rmds)]
# ifile <- rmds[grep("unit2.Rmd", rmds)]
# ifile <- rmds[grep("unit1-module2.Rmd", rmds)]
# ifile <- rmds[grep("cheatsheet", rmds)]
#ifile <- rmds[grep("syllabus", rmds)]
# ifile <- rmds[grep("unit1-module1", rmds)]
# ifile <- rmds[grep("unit2-module1", rmds)]
# ifile <- rmds[grep("unit2-module2a", rmds)]
# ifile <- rmds[grep("unit2-module2b", rmds)]
# ifile <- rmds[grep("unit1-module4", rmds)]
ifile <- rmds[grep("projects", rmds)]
# ifile <- rmds[grep("syllabus", rmds)]
ohtml <- here::here("docs",
                    paste0(gsub("\\.Rmd", "", basename(ifile)), ".html"))
rmarkdown::render(input = ifile, output_file = ohtml)

```


## Index render
```{r}
rmarkdown::render(input = here::here('docs/index.Rmd'),
                  output_file = here::here('docs/index.md'))
rmarkdown::render(input = here::here('docs/index.Rmd'),
                  output_file = here::here('docs/index.html'))
rmarkdown::render(input = here::here('docs/index_detailed.Rmd'),
                  output_file = here::here('docs/index_detailed.html'))
```
