---
title: "Geography 246/346 Syllabus"
author: "Lyndon Estes, Zhiwen Zhu (TA)"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
    number_sections: yes
    toc_depth: 3
    toc: yes
vignette: >
  %\VignetteIndexEntry{syllabus}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Originally developed for statistics, free and open source R is now one of the most widely used programming languages in both industry and academia. Among its many applications, R is increasingly used for geospatial analyses, as evidenced by its growing ecosystem of spatial libraries (covering everything from basic vector and raster manipulation to advanced modeling and image processing), the evolution of classes for representing spatial data, its expanding capacity to interact with and leverage the capabilities of other geospatial libraries (GDAL) and GIS (e.g. GRASS, QGIS, PostGIS, SAGA).  Alongside its geospatial capabilities, there has been concurrent development of interactive development environments (IDEs) for R, which facilitate the creation, presentation, and reproducibility of analyses. R has therefore very close to being a one-stop shop for the modern GIScientist. This course will provide students with the skills they need to use R as a GIS. There will be additional emphases on programming, presentation, and reproducibility, which will entail learning to develop R libraries, development of presentations and reports using Rmarkdown, and using version control with github. Students will learn and apply R skills by working on a specific research problem. 

<a href="#top">Back to top</a>

## Philosophy
Although our primary focus is learning how to use `R` for geospatial analysis, the course also has a meta-goal, which is to introduce some additional skills and a mindset that together lead to more efficient and transparent, and thus ___reproducible___, research. Reproducibility is something I (Lyndon) only started to figure out (and am still learning) well after I completed by postdoc, but sincerely wish I had acquired before I started my PhD.  

## Caveats/things to consider
Here are some other aspects regarding this course that you may wish to consider before committing: 

1. ___Assignments in this class are problem-oriented, not recipe-based___: 

    I believe that the best way to learn R (and any human or computational language, for that matter) is to figure out how to use it to solve specific problems. There are usually multiple paths that can be taken to solve a problem, particularly in R, which has a huge number of contributors and over 10,000 packages. Coding recipes that spell out the precise steps needed to arrive at a solution will not take you as far towards R fluency, and will prevent you from learning the diversity of this language. 
    
    I find it very rewarding to figure out programming problems (and I even prefer programming to writing papers), but some people can find it boring or even frustrating. If you fall into the latter camp, please consider the possibility that this course might not be for you. Let's discuss.
    
2. ___The order in which material is introduced will occasionally be non-linear___: 

    Primarily because we are introducing the concept of reproducibility up front in this class, which entails learning about some things that people might ordinarily get around to after they know a bit of R code.  However, I believe that this order of things will enable you to learn R (or any other programming language) more rapidly. It will also (hopefully) make learning R more fun. 

3. ___This is a flipped class___:

    All materials and problems are expected to be done before class.  With few exceptions, there will be no lectures. Class time is for helping you to work through problems that you are having, clarifying concepts that are unclear, or for presenting your work to your peers. That means that we expect you to have completed your work ahead of time so that you are already aware of the problems you are having.  
    
    We have adopted this structure because of the problem-oriented nature of assignments. 
    
4. ___I am not a computer scientist___:

    Full disclosure: I am self-taught programmer. That means that the way I teach this course might differ from the way a formally trained computer or (even data) scientist would teach it. I don't know if that's the case, but those of you have taken computer science courses might notice some differences. 
    
5. ___This is a new course___: 

    We are developing this course for Clark for the first time. Much of it will be developed as the semester unfolds, building out material onto the existing three unit framework. This approach will allow us to adapt the pace and material as needed to match progress.  The disadvantage is that you will not see from Day 1 the exact materials we will be covering for later sections (e.g. Unit 2). 

<a href="#top">Back to top</a>
    
## Required Texts, Reading, and Assignments
There are no required texts for this course, at least not ones that you have to buy. There is a huge amount of well-developed R material that is freely available on the web, and we are going to draw on that for this class. You will find links to that material in the syllabus, and, in some cases, in the [Resources](#Resources) section below.

__Readings__ should be completed ___before___ the class they are listed under. E.g. By the time you arrive for the first class on Monday, August 28th, you should have done the readings. Also, since many of the assigned readings present example code and practical work, you should be running those examples as you read. This is a key part of learning the language, and this part of the course is separate from the practicals. 

___Practical assignments___. During the first two units, we will give a number of practical exercises (see links to individual assignments in the [course structure](#structure) section). Unless otherwise stated, these will be assigned on a Monday and due by midnight on Friday of the same week. These assignments will ask you to apply skills from the readings to solve a particular problem. You will undertake and submit your work through github repositories that exist under the Agricultural Impacts Research Group's github [organization](https://github.com/agroimpacts), where there is a [team](https://github.com/orgs/agroimpacts/teams/geog246346) setup for this class. That means that you will need to join github (it's free!) to be able to submit assignments, as we will need your github name to add you to the team. You will manage your individual assignments under private personal repositories that will be listed under your own individual sub-team.   

__Projects__ Each student will be required to undertake a final project. Please see the [projects](projects.html) page for more detail.

A note on writing code: there are many ways to write code and get the results you want. However, not all ways of writing code are equal. Some code is messy and hard to read. Other code is organized, clean, and easy to read. The latter is what we are aiming for, as it helps to foster reproducibility. In this class, we will follow [Hadley Wickham's style guide](http://adv-r.had.co.nz/Style.html). Please study it.    

<a href="#top">Back to top</a>

## Assessment

Your progress in this class will be assessed based on: 

1. Practical assignments in Units 1 and 2 (30% of grade)
2. Semester projects: 
    a. Oral presentation (30%)
    b. Final report/paper (40%)

Grading will be based on the rubrics found under the [Assessment](assessment.html) vignette 

<a href="#top">Back to top</a>

## Expectations
Since our class is a computer lab, no food or drink I am sad to say (because I usually like to have a tea with me :( ). Since class is flipped, this is a time for questions and discussion, between us and you, and often between yourselves. However, please keep any conversations low and necessary to the task at hand if they are one-on-one, as we don't want necessary class-wide conversations drowned out.   

For assignments in the first two units, students can work together to figure out coding problems and to understand the material, but final assignments should reflect each student's own work and coding effort (i.e. not copying code from someone else). For final projects, many, if not most, of the projects will be team-based (2-3 per team, depending on the nature of the assignment) on some if not all of the available topics.

We abide by, and will enforce, the University's policies on plagiarism and cheating. 

### Communications
We will conduct class communications via a Slack channel that you should already be invited to. Please don't send emails. We chose to use Slack because it keeps relevant conversations in defined places, rather than scattered across email inboxes. We will have a few channels that are designated for specific kinds of conversations. The \#general channel will be used for course announcements, etc. There will be a specific channel for discussion about each assignment. Any questions you have about the assignment should be asked in those. You can send private individual or group messages that are restricted to those individuals in the conversation. Use this for confidential questions.  

Slack's most obvious characteristic is instant messaging. However, please don't approach it as an instant messenger, at least with respect to Zhiwen and myself and how quickly you want a response from us. While I always strive to be responsive, given workloads and the number of students enrolled, we have to restrict responses to specific days and times. Since we are running this class as a flipped model, the goal is for all questions to be answered during class (which will be more like lab than lecture). Outside of class times, we will have the following physical and Slack (meaning we will respond to Slack messages during those times) office hours, to which any other course-related communications should be confined. 

Instructor | Office           | Office hours     | Slack hours
---------|------------------|------------------|-------
Lyndon   | Jefferson 107    | Tuesday 1-3 pm   | Wednesday 2-4 pm 
Zhiwen   | Jefferson Cofert | Thursday 9-11 am | Friday 10 am-12 pm

Also, please feel free to give any ___constructive___ feedback, positive or negative (and it can be an anonymous note, if you are more comfortable), regarding the course or how we are teaching it.  This will be appreciated, and can help make the course better for everyone. 

<a href="#top">Back to top</a>

# Course structure{#structure}
The follow is an overview of the course structure. Note that this structure will evolve during the semester, given that this is its first run, and we will adjust material to match the pace of learning. 

## Unit 1. *An introduction to R and related reproducibility skills*

In this first part of the course, we will learn the basics of working with R, starting with non-spatial data. We will also learn some additional skills that foster ___reproducibility___, which can be loosely defined as the ability for you and others to *easily* repeat the steps of your analysis.  including the use of `git` and [github](https://github.com), how to create an R package, and the use of `Rmarkdown` to document and present your analyses. 

### Week 1. Overview of R and Reproducibility
#### Class 1 (28 Aug). The nature and history of R
+ Readings:
    + Read the syllabus
    + R overview and history:
        + [Watch this online lecture by Roger Peng](https://www.youtube.com/watch?v=STihTnVSZnI)
        + Difference between python and R
        + [Read the introduction section](http://adv-r.had.co.nz/Introduction.html) here by Hadley Wickham
        + [Introduction](http://www.rspatial.org/intr/rst/1-introduction.html) chapter in rspatial's Introduction to R, and Chapters 1 and 2 (pgs 1-7) in [R for beginners](https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf), which is linked from that (there are other interesting links in there)
    + [A video introduction to Rstudio](https://www.youtube.com/watch?v=pXd54-vucu0)
+ Assignment: Sign up for [github](https://github.com) and send us your github user name (by Sunday evening, preferably)

#### Class 2 (30 Aug). Reproducibility and its components
+ Readings: 
    + [The Practice of Reproducible Research](https://www.gitbook.com/book/bids/the-practice-of-reproducible-research/details), specifically: 
        + Paragraphs 1-12 in the [Introduction](https://www.practicereproducibleresearch.org/core-chapters/1-intro.html)
        + [Assessing Reproducibility](https://www.practicereproducibleresearch.org/core-chapters/2-assessment.html)
        + [The Basic Reproducible Workflow Template](https://www.practicereproducibleresearch.org/core-chapters/3-basic.html)
    + Skim [Sandve et al (2013)](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285) 
    + Why you should (and, in this class, will) structure your work as an R package: Read [this](https://hilaryparker.com/2013/04/03/personal-r-packages/), 
    [this](http://kbroman.org/pkg_primer/), and [this](http://r-pkgs.had.co.nz/intro.html)...
    + ...and use git and GitHub with R and Rstudio: Read [this](http://r-pkgs.had.co.nz/git.html#git), [this](https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control), and [this](https://jahya.net/blog/git-vs-github/).  

### Week 2. Reproducibility Continued
#### Class 3 (6 Sep). Rmarkdown and more on R packages
+ Readings:
    + Two quick things on markdown: [One](http://kbroman.org/knitr_knutshell/pages/markdown.html); [Two](http://blog.kdheepak.com/writing-papers-with-markdown.html)
    + Which leads to a bit about Rmarkdown: [A quick overview](http://kbroman.org/knitr_knutshell/pages/Rmarkdown.html); and see [Rstudio's Overview of Rmarkdown](http://rmarkdown.rstudio.com/)--click "Get Started" and then go through all the linked sections (Introduction through Cheatsheets).  
    + Writing R packages: 
        + [A very short tutorial](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/)--note: Step0 in this tutorial is *likely* done already (check the packages tab in RStudio to confirm); 
        + More details on packages from Hadley Wickham's book. Review these chapters (somewhat long, so probably just read): [Packages](http://r-pkgs.had.co.nz/package.html#package-structure); [R code](http://r-pkgs.had.co.nz/r.html#r); [Package metadata](http://r-pkgs.had.co.nz/description.html#description); [Documentation](http://r-pkgs.had.co.nz/man.html#man); [Vignettes](http://r-pkgs.had.co.nz/man.html#man) (also read [this](http://rmflight.github.io/posts/2014/07/analyses_as_packages.html) about vignettes); [Namespace](http://r-pkgs.had.co.nz/namespace.html#namespace); [External data](http://r-pkgs.had.co.nz/data.html#data); the part about [Tests](http://r-pkgs.had.co.nz/tests.html#tests) is also important, but for your own future work--we won't get that far in this class. 
    + Poke around the [ROpenSci website](https://ropensci.org), and particularly its section on [tools for reproducibility](http://ropensci.github.io/reproducibility-guide/sections/tools/) to get a bigger picture view of how R fits into reproducibility 
+ [Assignment 1](assignments/assignment1.html). 

### Week 3. R fundamentals

#### Class 4 (11 Sep). R bestiary
+ Readings: 
    + Beginning note: some of this material is quite advanced, but we are going to cover it as background so that we have a good idea of the major components of R. Although you may always find it useful to do practical examples as you read through material, for many of these you might just want to read to get an understanding. 
    + You may find it useful to refresh your memory with Chapters 1 and 2 (pgs 1-7) in [R for beginners](https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf)
    + Data types and structures: rspatial on [basic data types](http://www.rspatial.org/intr/rst/2-basic-data-types.html) and [basic data structures](http://www.rspatial.org/intr/rst/3-basic-data-structures.html), and Advanced R on [data structures](http://adv-r.had.co.nz/Data-structures.html)
    + (___Revisit___) Functions: rspatial's [chapter](http://www.rspatial.org/intr/rst/8-functions.html) on functions; read from top through "Primitive Functions" section in Advanced R's chapter on [Functions](http://adv-r.had.co.nz/Functions.html#function-components).  
    + Object-oriented programming (OOP) and R classes (especially S3 & S4): Read 5-5.1 in CRAN's [definition of OOP](https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Object_002doriented-programming) first, and then a [python-oriented version](https://python.swaroopch.com/oop.html) of the same, which might be somewhat clearer. Then read the Advanced R [OO field guide](http://adv-r.had.co.nz/OO-essentials.html) that talks about the main OOP-associated classes, particularly S3 and S4, used in R.
    + Environments: Read Environment Basics and Function Environments in the the [Environment chapter](http://adv-r.had.co.nz/Environments.html#env-basics) of Advanced R. 
+ [Assignment 2](assignments/assignment2.html)

#### Class 5 (13 Sep). Basic operations, indexing, and control structures
+ Readings: 
    + Basics: U. Illinois' [Using R as a calculator](http://courses.atlas.illinois.edu/fall2016/STAT/STAT200/RProgramming/RCalculator.html); rspatial's [chapter on algebra](http://www.rspatial.org/intr/rst/5-algebra.html); 
    + Indexing: rspatial on [indexing](http://www.rspatial.org/intr/rst/4-indexing.html)
    + Control structures: rspatial on [flow control](http://www.rspatial.org/intr/rst/10-flow.html), or control structures, and on R's unique [apply](http://www.rspatial.org/intr/rst/9-apply.html) family; an R-bloggers [more detailed look](https://www.r-bloggers.com/r-tutorial-on-the-apply-family-of-functions/) at family apply
    + Advanced control structures: [foreach](https://cran.r-project.org/web/packages/foreach/vignettes/foreach.pdf). Just read the introduction and skim the rest if you are so inclined--this is something to keep in our back pocket for future work
    + (___Revisit___) A bit more on functions from [here](https://ramnathv.github.io/pycon2014-r/learn/functions.html) and [here](http://www.statmethods.net/management/userfunctions.html)


### Week 4. Data preparation and visualization
#### Class 6 (18 Sep). Working with/manipulating data
+ Readings: 
    + Reading/writing data: [One piece](https://ramnathv.github.io/pycon2014-r/explore/tidy.html) by Ramnath that also introduces the concept of tidy data; [another from rspatial](http://www.rspatial.org/intr/rst/6-files.html)
    + Data massage (i.e. substitutions, reshaping, merging, or how to tidy up data): [rspatial's piece](http://www.rspatial.org/intr/rst/11-dataprep.html); [ramnath's take](https://ramnathv.github.io/pycon2014-r/explore/reshape.html) on it; [recoding data](http://www.cookbook-r.com/Manipulating_data/Recoding_data/), which is a sub-section of a very useful Cookbook for R section on [Manipulating Data](http://rprogramming.net/recode-data-in-r/) that you have the option of perusing further.  
    + Several of the previous readings introduce the `gsub` function, which uses *regular expressions* to match and replace patterns in character data types. Working with *regular expressions* is important and can be challenging, so let's read a [bit more](*regular expressions*) about them. Here's a [useful cheatsheet](https://www.rstudio.com/wp-content/uploads/2016/09/RegExCheatsheet.pdf) for that also. 
+ [Assignment 3](assignments/assignment3.html)

#### Class 7 (20 Sep). Visualization 
+ Readings:
    + The two schools of plotting in R: 
        + Base graphics, a useful intro by [rspatial](http://www.rspatial.org/intr/rst/12-plots.html), and [intermediate plotting](http://www.cyclismo.org/tutorial/R/intermediatePlotting.html#miscellaneous-options) from Kelly Black's R tutorial, and [this](http://shinyapps.org/apps/RGraphCompendium/index.php#miscellaneous) provides an excellent *(and optional)* reference for many different kinds of plots with code. 
        + ggplot/grammar of graphics: [A nice short bloggy intro](https://www.r-bloggers.com/a-simple-introduction-to-the-graphing-philosophy-of-ggplot2/), and Hadley Wickham's [longer walk-through](http://r4ds.had.co.nz/visualize.html#undefined). For reference, you might want to look at the [paper](http://vita.had.co.nz/papers/layered-grammar.pdf) describing the underlying philosophy
        

### Week 5. Analyses
#### Class 8  (25 Sep). Visualization
+ Regressions, correlations, non-parametric (splines): 
+ Downstream functions: summary, predict, etc. 

#### Class 9 (29 Sep). Reserved for spillover
+ Advanced data manipulation alternatives: data.table, dplyr (grammer of data)
    + The tidyverse
    + Possible [material](https://www.youtube.com/watch?v=9q7gssUP8UA)

<a href="#top">Back to top</a>

## Unit 2. Handling and analyzing spatial data with R
### Week 6 (Oct 2, 4). 
### Week 7 (Oct 11). 
### Week 8 (Oct 16, 18). 
### Week 9 (Oct 23, 25). 
### Week 10 (Oct 30, Nov 2). Visualization
### Key takeaways/skills

## Unit 3. Projects
### Week 11. 
### Week 12. 
### Week 13. 
### Week 14. 
### Week 15. 
### Key takeaways/skills

# Resources {#Resources}
The following are some helpful resources that you may wish to follow-up on as you learn R. 

## Books
[The R Inferno](http://www.burns-stat.com/pages/Tutor/R_inferno.pdf)

## The intertubes

### Bog-standard websites

[CRAN](https://cran.r-project.org), particularly an [Introduction to R](https://cran.r-project.org/doc/manuals/r-release/R-intro.html) the Task view [Analysis of Spatial Data](https://cran.r-project.org/web/views/Spatial.html)

[Tools for Reproducible Research](http://kbroman.org/Tools4RR/)

[R Exercises](http://www.r-exercises.com)

[ROpenSci](https://ropensci.org)

[Rmarkdown cheatsheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)

[Kelly Black's R tutorial](http://www.cyclismo.org/tutorial/R/#)

### Blogs/social

[R-bloggers](https://www.r-bloggers.com/)

[\@RLangTip](https://twitter.com/RLangTip)










