---
title: "Untitled"
author: "Mike Cecil"
date: "2023-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## RF Demo
- All code taken from https://geoscripting-wur.github.io/AdvancedRasterAnalysis/ 
- All code courtesy of Wageningen University & Research



---
```{r}
# Check for packages and install if missing
if(!"terra" %in% installed.packages()){install.packages("terra")}
if(!"sf" %in% installed.packages()){install.packages("sf")}
if(!"ranger" %in% installed.packages()){install.packages("ranger")}

library(terra)
library(sf)
library(ranger)

# Create data directory,
if (!dir.exists("data")) {
  dir.create("data")
}

# Create output directory
if (!dir.exists("output")) {
  dir.create("output")
}

# Download data and unzip
download.file("https://github.com/GeoScripting-WUR/AdvancedRasterAnalysis/releases/download/advrast-data/AdvancedRaster.zip", "data/AdvancedRaster.zip")
unzip("data/AdvancedRaster.zip", exdir="data")

# Load data and rename the layers
Gewata <- rast("data/S2B2A_T36NZP_20201227T075239_20m_gewata_crop.tif")
names(Gewata) <- readLines("data/S2B2A_T36NZP_20201227T075239_20m_gewata_bands.txt")

# The image is cloud-free, so drop the cloud mask layer
Gewata <- subset(Gewata, "SCL", negate = TRUE)

# Check out the attributes
Gewata$B02

# Some basic statistics using global() from the terra package
global(Gewata$B02, fun = "max")$max
global(Gewata$B02, fun = "mean")$mean

# What is the maximum value of all three bands?
global(Gewata, fun = "max")$max

# summary() is useful function for a quick overview
summary(Gewata$B02)

# Histograms for all the bands in one window (automatic, if a SpatRaster is supplied)
hist(Gewata, maxpixels = 1000)
```


---
```{r}
pairs(Gewata, maxpixels = 1000)
```

---
```{r}
par(mfrow = c(1, 1)) # reset plotting window
ndvi <- app(c(Gewata$B8A, Gewata$B04), fun = function(x){(x[1] - x[2]) / (x[1] + x[2])})
plot(ndvi)
```

---
```{r}
# Rescale to original scale
gewata <- app(Gewata, fun = function(x) x / 10000)

# Make a new SpatRaster by combining the Gewata and NDVI SpatRasters
covs <- c(gewata, ndvi)
plot(covs)
```


---
```{r}
names(covs) <- c(names(Gewata), "NDVI")
names(covs)
```

---
```{r}
# Download training polygons
download.file("https://github.com/GeoScripting-WUR/AdvancedRasterAnalysis/releases/download/advrast-data/trainingPoly.csv", "data/trainingPoly.csv")

# Load the training polygons from a csv file using st_read:
trainingPoly <- st_read("data/trainingPoly.csv")
```

---
```{r}
# Superimpose training polygons onto NDVI plot
par(mfrow = c(1, 1)) # reset plotting window
plot(ndvi)
plot(trainingPoly, add = TRUE)
```

---
```{r}
# Inspect the trainingPoly object
trainingPoly <- trainingPoly[, c(2:4)] #remove an unused column
trainingPoly
```

---

```{r}
summary(trainingPoly$Class)
trainingPoly$Class <- as.factor(trainingPoly$Class)
summary(trainingPoly$Class)
```

---
```{r}
# We can make a new 'Code' column by converting the factor levels to integer by using the as.numeric() function,
trainingPoly$Code <- as.numeric(trainingPoly$Class)

# Inspect the new 'Code' column
summary(trainingPoly$Code)
```

---
```{r}
# Define a colour scale for the classes (as above) corresponding to: cropland, forest, wetland
cols <- c("orange", "dark green", "light blue")

# Superimpose training polygons (colour by class) onto NDVI plot
plot(ndvi)
plot(trainingPoly["Class"], add = TRUE, pal = cols)

# Add a customised legend
legend("topright", legend = c("cropland", "forest", "wetland"), fill = cols, bg = "white")
```

---

```{r}
# Extract pixel values below the polygons into a dataframe
trainingData <- extract(covs, trainingPoly)

# Add a column specifying the class based on the polygon ID
trainingData$Class <- trainingPoly$Class[trainingData$ID]

# Remove the training polygon ID's from the dataframe
trainingData$ID <- NULL

head(trainingData, n = 10)
tail(trainingData, n = 10)
```

---
```{r}
val_crop <- subset(trainingData, Class == "cropland")
val_forest <- subset(trainingData, Class == "forest")
val_wetland <- subset(trainingData, Class == "wetland")

# NDVI
par(mfrow = c(3, 1))
hist(val_crop$NDVI, main = "cropland", xlab = "NDVI", xlim = c(0, 1), col = "orange")
hist(val_forest$NDVI, main = "forest", xlab = "NDVI", xlim = c(0, 1), col = "dark green")
hist(val_wetland$NDVI, main = "wetland", xlab = "NDVI", xlim = c(0, 1), col = "light blue")
```

---
```{r}
par(mfrow = c(1, 1))
# Scatterplot of bands 8a and 11 for the three classes
plot(B8A ~ B11, data = val_crop, pch = ".", col = "orange", xlim = c(0, 0.4), ylim = c(0, 0.5))
points(B8A ~ B11, data = val_forest, pch = ".", col = "dark green")
points(B8A ~ B11, data = val_wetland, pch = ".", col = "light blue")
legend("topright", legend = c("cropland", "forest", "wetland"), fill = c("orange", "dark green", "light blue"), bg = "white")
```

---
```{r}
library(ranger)

modelRF <- ranger(x = trainingData[, 1:ncol(trainingData)-1], 
                  y = trainingData$Class,
                  importance = "permutation", seed = 0xfedbeef)

```

---
```{r}
# Inspect the structure and element names of the resulting model
modelRF
class(modelRF)
str(modelRF)
names(modelRF)

# Inspect the confusion matrix of the OOB error assessment
modelRF$confusion.matrix

importance(modelRF)
```

---
```{r}
names(covs)
names(trainingData)
predLC <- predict(covs, modelRF, fun = function(...) predict(...)$predictions)
```

---
```{r}
# Plot the results
# Recall: 1 = cropland, 2 = forest, 3 = wetland
cols <- c("orange", "dark green", "light blue")
plot(predLC, col = cols, legend = FALSE)
legend("bottomright",
       legend = c("cropland", "forest", "wetland"),
       fill = cols, bg = "white")
```



---
```{r}
# Make an NA-value raster based on the LC raster attributes
formask <- setValues(predLC, NA)

# Assign 1 to formask to all cells corresponding to the forest class
formask[predLC == 2] <- 1
plot(formask, col = "dark green", legend = FALSE)
```

---
```{r}
# Group raster cells into patches based on the Queen's Case
if(!file.exists(fn <- "output/clumformask.tif")) {
  forestpatches <- patches(formask, directions = 8, filename = fn)
} else {
  forestpatches <- rast(fn)
}

plot(forestpatches, col = topo.colors(nrow(forestpatches)))
```

---
```{r}
# Assign frequency table (to a dataframe)
patchFreq <- freq(forestpatches)

# Inspect the dataframe
head(patchFreq)
tail(patchFreq)
```

---
```{r}
# Which rows of the data.frame are only represented by one cell?
str(which(patchFreq$count == 1))

# Which values do these correspond to?
str(patchFreq$value[which(patchFreq$count == 1)])

# Put these into a vector of patch ID's to be removed
excludeID <- patchFreq$value[which(patchFreq$count == 1)]

# Make a new forest mask to be sieved
formaskSieve <- formask

# Assign NA to all patches whose IDs are found in excludeID
formaskSieve[forestpatches %in% excludeID] <- NA

## Zoom in to a small extent to check the results
# Note: you can also define your own zoom by using e <- drawExtent()
e <- ext(c(830000, 834000, 830000, 834000))
par(mfrow = c(1, 2)) # allow 2 plots side-by-side
plot(formask, ext = e, col="dark green", legend = FALSE, main = 'formask')
plot(formaskSieve, ext = e, col="dark green", legend = FALSE, main = 'formaskSieve')
```



