---
title: "Geospatial Analysis with R"
subtitle: Class 14
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["default", "lucy", "middlebury-fonts", "themes/class14plus.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r, message=FALSE, eval=FALSE, warning=FALSE}
library(leaflet)
library(sf)
library(dplyr)
districts <- read_sf(system.file("extdata/districts.shp", package = "geospaar"))
bb <- unname(st_bbox(districts))
xy <- st_centroid(districts) %>% st_coordinates() %>% 
  bind_cols(name = districts$distName, .)
slist <- list("color" = "white")
label_opts <- labelOptions(noHide = TRUE, style = slist, direction = 'center',
                           textOnly = TRUE, textsize = "5px")

m <- leaflet() %>% 
  addProviderTiles("Esri.WorldImagery") %>% 
  fitBounds(bb[1], bb[2], bb[3], bb[4]) %>% 
  addPolygons(data = districts, fill = FALSE, color = "white", 
              group = "Districts", weight = 1) %>% 
  addLabelOnlyMarkers(xy$X, xy$Y, label = xy$name, group = "Names",
                      labelOptions = label_opts) %>%
  addLayersControl(overlayGroups = c("Districts", "Names"),
                   options = layersControlOptions(collapsed = FALSE,
                                                  autoZIndex = FALSE))
```
```{r, eval=FALSE, echo=FALSE}
library(htmlwidgets) 
saveWidget(m, "docs/figures/zambialeaflet.html")
```



---

<iframe seamless src="figures/zambialeaflet.html" width="100%" 
height="500"></iframe>


---

## Today

### Intro to Spatial

- Non-spatial to spatial
- Read and write spatial
- CRS
- Make data from scratch
- Spatial properties

---

### Non-spatial to spatial

- Read in farmer data
```{r, eval = FALSE}
library(tidyverse)
library(sf)
farmers <- system.file("extdata/farmer_spatial.csv", package = "geospaar") %>% 
  read_csv() 
farmers_sf <- st_as_sf(farmers, coords = c("x", "y"), crs = 4326)
```

- Write and read the spatial data
```{r, eval=FALSE}
write_sf(farmers_sf, dsn = "external/notebooks/data/farmers_spatial.geojson")
farmers_sf <- read_sf("external/notebooks/data/farmers_spatial.geojson")
districts <- read_sf(system.file("extdata/districts.shp", package = "geospaar"))
roads <- read_sf(system.file("extdata/roads.shp", package = "geospaar"))
```

---
  
### Wrangle spatial data
```{r, eval = FALSE}
farmers %>% filter(uuid == "009a8424")
farmers_sf %>% filter(uuid == "009a8424")
farmers_sf %>% group_by(uuid) %>% summarize(n = n()) %>% 
  arrange(n) %>% st_geometry %>% plot(pch = 16, cex = 0.5)
farmers_sf %>% arrange(uuid)
class(farmers_sf)
# intersection with st_join and left = FALSE to remove plots outside of Zambia
farmers_sf_trim <- farmers_sf %>% group_by(uuid) %>% summarize(n = n()) %>% 
  st_join(., districts, left = FALSE)
plot(st_geometry(districts))
farmers_sf %>% group_by(uuid) %>% summarize(n = n()) %>% st_geometry %>% 
  plot(pch = 16, add = TRUE, cex = 1)
farmers_sf_trim %>% st_geometry %>% 
  plot(pch = 16, add = TRUE, col = "red", cex = 0.5)
```

---
### Make spatial data

```{r, eval = FALSE}
pts <- st_multipoint(x = cbind(x = c(27.5, 28, 28.5), y = c(-14.5, -15, -15.5)))
pts <- st_geometry(pts) %>% st_as_sf() %>% st_cast("POINT") %>% 
  cbind(ID = 1:nrow(.), .)
pol <- st_polygon(list(cbind(x = c(26.5, 27.5, 27, 26, 26.5), 
                             y = c(-15.5, -16.5, -17, -16, -15.5))))
pol <- st_geometry(pol) %>% st_as_sf() %>% cbind(ID = 1:nrow(.), .)
sline <- st_linestring(cbind(x = c(27, 27.5, 28), y = c(-15, -15.5, -16)))
sline <- st_geometry(pol) %>% st_as_sf() %>% cbind(ID = 1:nrow(.), .)
```

---
### Spatial properties
```{r, eval=FALSE}
pol %>% st_area
pol %>% st_sf(crs = 4326) %>% st_area
sline %>% st_sf(crs = 4326) %>% st_length
```

---
### Spatial transforms
```{r, eval=FALSE}
pol %>% st_sf(crs = 4326) %>% st_transform(., st_crs(roads)) %>% st_area
```





