---
title: "Unit 2 - Handling and analyzing spatial data with R"
date: "`r Sys.Date()` [Back to home](https://agroimpacts.github.io/geospaar/)"
output:
  rmdformats::readthedown:
    highlight: pygments
    fig_caption: yes
    number_sections: yes
    toc_depth: 4
    css: unit.css
vignette: >
  %\VignetteIndexEntry{Unit 2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

# Overview{#unit2overview}

In this unit we finally begin to start working with spatial data. We will learn to use R to do the types of analyses you typically associate with traditional GIS software, such as Idrisi/Terrset, ArcGIS, QGIS, and friends. We will also continue to use and build on the basic R programming and reproducibility skills you learned in [Unit 1](unit1.html). 

Three assignments will be given during this unit. You should also finalize the subject of your final project before the end of this unit, begin to assemble the data you need, and outline the approach you plan to use. The more effort you put into planning (and even beginning the analysis for) your project, the more `R` skills you will acquire. Why? Because you will be be thinking about how to use `R` to help you solve problems that you are interested in, which requires more exploration and creativity than simply tackling assignments that I give you. Since people will be doing different projects, there is also more potential for peer-to-peer learning, as you learn about and share different aspects of `R`.

The learning goals for this unit are as follows - by the end of this unit, you should: 

- ___Understand/know___: the strengths and limitations of working with spatial data in `R`; possible workarounds for these limitations; the primary external libraries (e.g. GDAL, GEOS, and PROJ.4) that `R` (and many other GIS) uses to provide spatial capabilities, and understand the changes that are coming down the track with respect to `R` and spatial data applications

- Be able to do ___the following___: perform basic vector operations (intersections, unions, differences) and manipulations (merges/joins); raster operations (algebra, focal analyses, terrain characteristics) and manipulations (aggregate/disaggregate, resample, reproject); convert rasters to vectors and vice versa; visualize spatial data; extract quantities/statistics from spatial data; run spatial models and map their predictions; do some basic remote sensing analyses; get help on R-sig-geo (i.e. know how to create a reproducible examples)   

# Unit modules 

This section is broken into three modules (the materials can be accessed by following the links): 

[**Module 1**](unit2-module1.html): Working with spatial vector data 

[**Module 2**](unit2-module2.html): Working with raster data

[**Module 3**](unit3-module3.html): Spatial modeling and remote sensing

[**Appendix**](unit2-appendix.html): Unit appendix


***
<center>
[Back to home](toc.html)
</center>
***
